[package]
name = "hypertile-sys"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "PyO3 bindings and bilingual stepping engine for Hypertile"

[lib]
name = "hypertile_sys"
crate-type = ["cdylib", "rlib"]

[dependencies]
hypertile-core = { version = "0.1.2", path = "../hypertile-core" }
pyo3 = { version = "0.29", features = ["extension-module"] }
parking_lot = "0.12"
