"""Type stubs for the native Rust C-extension module _hypertile_sys."""

import types
from collections.abc import Callable, Generator, Sequence
from typing import Any, Self

class CancellationToken:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    def is_cancelled(self) -> bool: ...
    def throw_if_cancelled(self) -> None: ...

class RegisteredWorker:
    def worker_id(self) -> int: ...
    def run_one(self) -> bool: ...
    def run_until_idle(self) -> None: ...
    def deregister(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None = None,
        exc_val: BaseException | None = None,
        exc_tb: types.TracebackType | None = None,
    ) -> None: ...

class NativeTask:
    def done(self) -> bool: ...
    def result(self) -> bytes: ...
    def add_done_callback(self, cb: Callable[[], Any]) -> None: ...
    def __await__(self) -> Generator[Any, None, bytes]: ...

class CallableTask:
    def done(self) -> bool: ...
    def result(self) -> Any: ...
    def add_done_callback(self, cb: Callable[[], Any]) -> None: ...
    def __await__(self) -> Generator[Any, None, Any]: ...

class BatchNativeTask:
    def done(self) -> bool: ...
    def result(self) -> list[bytes]: ...
    def add_done_callback(self, cb: Callable[[], Any]) -> None: ...
    def __await__(self) -> Generator[Any, None, list[bytes]]: ...

class BatchCallableTask:
    def done(self) -> bool: ...
    def result(self) -> list[Any]: ...
    def add_done_callback(self, cb: Callable[[], Any]) -> None: ...
    def __await__(self) -> Generator[Any, None, list[Any]]: ...

class PanicInTask(Exception): ...
class TaskCancelled(Exception): ...
class RegistrationError(Exception): ...

def is_free_threaded() -> bool: ...
def register_worker(kind: str = "bilingual") -> RegisteredWorker: ...
def spawn_coroutine(
    coro: Any,
    done_callback: Callable[..., Any] | None = None,
    cancellation_token: CancellationToken | None = None,
) -> None: ...
def run_level1(main_coro: Any) -> Any: ...
def native_pipeline_transform(payload: bytes, rounds: int = 100) -> bytes: ...
def spawn_native_pipeline(payload: bytes, rounds: int = 100) -> NativeTask: ...
def batch_spawn_native_pipeline(
    payloads: Sequence[bytes], rounds: int = 100
) -> BatchNativeTask: ...
def spawn_callable(
    func: Callable[..., Any],
    args: tuple[Any, ...] | None = None,
    kwargs: dict[str, Any] | None = None,
) -> CallableTask: ...
def batch_spawn_callable(
    func: Callable[..., Any], args_list: Sequence[tuple[Any, ...]]
) -> BatchCallableTask: ...
