[package]
name = "hypertile-capi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Lightweight extern C ABI for the Hypertile work-stealing runtime"

[lib]
name = "hypertile_capi"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
hypertile-core = { version = "0.1.2", path = "../hypertile-core" }
parking_lot = "0.12"
crossbeam-utils = "0.8"
